name: 'Label Pull-request Conventionally'
description: 'Labels the pull-request that triggered the calling workflow by its branch/prefix'
author: 'oblivioncth'
runs:
  using: 'composite'
  steps:
    - name: Label master PR
      if: github.base_ref == 'master'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: release-pr
    - name: Label bugfix PR
      if: startsWith(github.head_ref, 'bugfix/')
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: bug
    - name: Label feature PR
      if:  startsWith(github.head_ref, 'feature/')
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: enhancement
    - name: Label backend PR
      if:  startsWith(github.head_ref, 'backend/')
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: backend