name: 'Merge branches'
description: 'Merges the target branch into the source branch'
author: 'oblivioncth'
inputs:
  source_branch:
    required: false
    description: "The source branch to merge from"
    default: '' # Current branch
  target_branch:
    required: true
    description: "The target branch to merge into"
  ff:
    required: false
    description: "ff strategy: yes, no, only, default"
    default: default

runs:
  using: 'composite'
  steps:
  - uses: oblivioncth/actions/.github/self_link@dev
  - name: Merge branches
    id: proj-checkout
    uses: ./.this_repo/git/smart-checkout
  - name: Merge
    shell: pwsh
    working-directory: ${{ steps.proj-checkout.outputs.path }}
    env:
        ff: ${{ inputs.ff }}
        source: ${{ inputs.source_branch }} 
        target: ${{ inputs.target_branch }}
    run: |
      $ff="$Env:ff"
      $ff_opt=$(($ff -eq "yes") ? "--ff" : ($ff -eq "no") ? "--no-ff" : ($ff -eq "only") ? "--ff-only" : "")
      $source=($Env:source -ne "") ? "$Env:source" : "${{ github.ref_name }}"
      $current_branch=$(git branch --show-current) # Restore when done
      git checkout $Env:target
      git merge $source $ff_opt
      git push
      git checkout $current_branch
        