name: 'Get CMake project version'
description: 'Gets the project version set in the repositories root CMakeLists.txt (assumes literal value)'
author: 'oblivioncth'
outputs:
  version:
    description: 'The version number'
    value: ${{ steps.get-version.outputs.version }}
runs:
  using: 'composite'
  steps:
  - uses: oblivioncth/actions/.github/self_link
  - name: Checkout Project
    id: proj-checkout
    uses: ./.this_repo/git/smart-checkout
  - name: Get version
    id: get-version
    shell: pwsh
    env:
      repo_path: ${{ steps.proj-checkout.outputs.path }}
    run: |
      cd "${{ env.repo_path }}"
      echo "Getting project version number from CMakeLists.txt..."
      $project_file = Get-Content -Raw CMakeLists.txt
      
      # The (?s) is a pwsh specific "miscellaneous construct" that enables single-line mode for
      # the '.' character (i.e. /s for PCRE), and not part of the actually expression
      if(!($project_file -match '(?s)project\(.*?\s+VERSION\s+(?<projver>\S+)[\)\s]')){
        throw "Could not get project version!"
      }
      $proj_version = $Matches.projver
      echo "Version is '${proj_version}'"
      echo "version=$proj_version" >> $Env:GITHUB_OUTPUT
      
        