name: Sync Secrets Beteween Repos
on:
  workflow_dispatch:

jobs:
  sync-secrets:
    name: Sync Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: jpoehnelt/secrets-sync-action@v1.9.0
        env:
          OBYBOT_FFYNNON_ACCESS: ${{ secrets.OBYBOT_FFYNNON_ACCESS }}
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}
          secrets: |
            ^OBYBOT_FFYNNON_ACCESS
          repositories: |
            .* # All
            
