# Keep updated with paths that should trigger this automatically

name: Sync Files To Other Repos
on:
  push:
    branches:
      - master
    paths:
      - '.github/release.yml'
  workflow_dispatch:

jobs:
  sync-files:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Get oby token
        id: get-token
        uses: ./.github/get-oby-token
        with:
          key: ${{ secrets.OBY_KEY }}
      - name: Get repo list
        id: get-repos
        uses: ./github/get-repo-list
        with:
          token: ${{ steps.get-token.outputs.token }}
          exclude_forks: true
          exclude_private: true
          exclude_regex: |
            ^oblivioncth/actions
      - run: npm install js-yaml
      - name: Generate sync config
        uses: actions/github-script@v7
        id: gen-config
        env:
          repos: ${{ steps.get-repos.outputs.repos }}
          template: ./.github/files-sync-config.yml.in
          gen: ./.github/files-sync-config.yml
        with:
          github-token: ${{ steps.get-token.outputs.token }}
          script: |
            // Modules
            const fs = require('fs');
            const yaml = require('js-yaml');
            const assert = require('node:assert/strict');

            // Files
            const templatePath = process.env.template;
            const generatedPath = process.env.gen;

            // Read original yaml
            const template = yaml.load(fs.readFileSync(templatePath, 'utf8'));
            assert(template.patterns.length == 1, "More than one template pattern not accounted for!");
            assert(template.patterns[0].repositories === null, "Template pattern repositories is not null!");

            // Get input list
            const repos = JSON.parse(process.env.repos);
            assert(Array.isArray(repos), "Input repo list is not array!");
            assert(repos.every(item => typeof item === 'string'), "Input repo list is not all strings!");

            // Create repo list
            template.patterns[0].repositories = repos.map((r) => r + '@dev');

            // Write generated yaml
            const generated = yaml.dump(template);
            console.log(`Generated sync config:\n${generated}`);
            fs.writeFileSync(generatedPath, generated, 'utf8');
      - name: Sync
        id: sync
        uses: wadackel/files-sync-action@v3
        with:
          github_token: ${{ steps.get-token.outputs.token }}
      - name: Mark PRs as auto-merge
        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.get-token.outputs.token }}
        run: |
          $jsonUrls = '${{ steps.sync.outputs.pull_request_urls }}'
          $urls = $jsonUrls | ConvertFrom-Json
          foreach ($url in $urls) {
            Write-Output "Setting auto-merge for '$url'"
            gh pr merge --merge --auto --delete-branch "$url"
          }

