name: Sync Secrets Beteween Repos
on:
  workflow_dispatch:

# Syncs secrets to ALL repos for now, even if they don't need them
jobs:
  sync-secrets:
    name: Sync Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Get oby token
        id: get-token
        uses: ./.github/get-oby-token
        with:
          key: ${{ secrets.OBY_KEY }}
      - name: Sync
        uses: jpoehnelt/secrets-sync-action@v1.10.0
        env:
          OBYBOT_FFYNNON_ACCESS: ${{ secrets.OBYBOT_FFYNNON_ACCESS }}
        with:
          github_token: ${{ steps.get-token.outputs.token }}
          secrets: |
            ^OBYBOT_FFYNNON_ACCESS
          repositories: |
            .*

