# Keep updated with paths that should trigger this automatically

name: Sync Files To Other Repos
on:
  push:
    branches:
      - master
    paths:
      - '.github/release.yml'
  workflow_dispatch:

jobs:
  sync-files:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Get oby token
        id: get-token
        uses: ./.github/get-oby-token
        with:
          key: ${{ secrets.OBY_KEY }}
      - name: Sync
        uses: wadackel/files-sync-action@v3
        with:
          github_token: ${{ steps.get-token.outputs.token }}
          config_file: .github/files-sync-config.yml
      - name: Sync 2
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          gh_pat: ${{ steps.get-token.outputs.token }}
          is_fine_grained: true