on:
  workflow_call:
    
jobs:
  label-pr:
    name: Label issue
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Sync labels
        uses: oblivioncth/actions/labels/sync-labels@v1

# Just syncs for now